# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-fixesproto
Summary:    X.Org X11 Protocol fixesproto
Version:    5.0
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/fixesproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-fixesproto.yaml
Patch0:     build-fix.patch
Provides:   fixesproto


%description
Xorg X11 Protocol fixesproto



%prep
%setup -q -n fixesproto-%{version}

# build-fix.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/fixesproto.pc
%{_includedir}/X11/extensions/xfixeswire.h
%{_includedir}/X11/extensions/xfixesproto.h
%doc %{_datadir}/doc/fixesproto
# << files


